//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPureGold.Domain.Models.WeichertCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbNameType
    {
        public tbNameType()
        {
            this.tbNameToRoles = new HashSet<tbNameToRole>();
        }
    
        public string NAMECD { get; set; }
        public string NAMEDESC { get; set; }
    
        public virtual ICollection<tbNameToRole> tbNameToRoles { get; set; }
    }
}
